# Generated by Django 4.2.1 on 2024-12-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Username')),
                ('role', models.CharField(blank=True, choices=[('director', 'Director'), ('manager', 'Manager'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=15, null=True, verbose_name='Role')),
                ('premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
    ]
