# Generated by Django 4.2.1 on 2024-12-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_series_movie_part_remove_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='invisible',
            field=models.BooleanField(default=True, verbose_name='Invisible'),
        ),
    ]
