# Generated by Django 4.2.1 on 2024-12-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_invisible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='invisible',
            field=models.BooleanField(default=False, verbose_name='Invisible'),
        ),
    ]
