# Generated by Django 4.2.1 on 2024-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_invisible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='part',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Part'),
        ),
    ]
